---
title: "astronauts"
author: "Gavin Fay"
date: "7/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#devtools::install_github("GuangchuangYu/emojifont")
library(emojifont)
library(patchwork)
load.fontawesome()
library(png)
library(ggimage)
```


### TidyTuesday 2020
## week 29, 2020-07-14, astronauts
<https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-07-14/readme.md>


```{r}
truth_theme <- theme_minimal() +
  theme(
     plot.margin = margin(.25, 0.15, .25, 0.15, "cm"),
   plot.background = element_rect(fill = "black"),
   axis.line = element_line(color = "white"),
   axis.text = element_text(color = "white", size = 12),
   text = element_text("mono", color = "white"),
   plot.title = element_text(size = 14),
   plot.subtitle = element_text(size = 12),
   axis.title.x = element_text(size = 10),
   axis.title.y = element_text(size = 10),
   axis.text.x = element_text(size = 8),
   axis.text.y = element_text(size = 8),
   panel.grid = element_blank())

```


## get data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 29)
astronauts <- tuesdata$astronauts
astronauts
```

## look at total # hours in space by year

```{r}
tot_hours <- astronauts %>% 
  # group_by(year_of_mission, mission_title) %>% 
  # slice(1) %>% 
  # ungroup() %>% 
  group_by(year_of_mission) %>% 
  summarize(mission_hours = sum(hours_mission, na.rm = TRUE),
            eva_hours = sum(total_eva_hrs)) %>% 
  mutate(prop_mission_hours = mission_hours/(24*365),
         prop_eva_hours = eva_hours/(24*365)) %>% 
  rename(year = year_of_mission) %>% 
  pivot_longer(cols = -(year)) %>% 
  I()
tot_hours

```

## UFO sightings

```{r}
ufo_sightings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")
ufos <- ufo_sightings %>% 
  separate(date_time, into = c("month", "day", "year")) %>%
  mutate(year = as.numeric(year)) %>% 
  group_by(year) %>% 
  summarize(sightings = n()) %>% 
  I()

```

## icons
```{r}
 naut <-"icons8-astronaut-48.png"
 alien <- "icons8-alien-48.png"

```

## plot of chance there is an astronaut on a spacewalk
```{r}
p1 <- tot_hours %>% 
  filter(name == "prop_eva_hours") %>% 
  ggplot() +
  aes(x=year, y = value) +
  theme_minimal() +
  labs(x = "Year",
       y = "P(EVA) by hr ") +
  geom_image(aes(x = year, y = value, image = naut), size=.075)+
  truth_theme +
  theme(plot.subtitle = element_text(hjust = -0.5),
             plot.margin = margin(.5, 0.15, .15, 0.15, "cm")) +
  NULL
```


## correlations between UFOs and astronauts
```{r}
both <- tot_hours %>% 
  left_join(ufos) %>% 
  I()
```
```{r}
res <- both %>% 
  ggplot() +
  aes(x = value, y = sightings, group = name, col = name) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm") +
  facet_wrap(~name, scales = "free") +
  NULL
res
```

```{r}
lm_results <- both %>% 
  group_by(name) %>% 
  nest() %>% 
  mutate(model1 = map(data, ~lm(value~year, data = .)),
         model2 = map(data, ~lm(sightings~value, data =.))) %>% 
  pivot_longer(cols = c(model1, model2), names_to = "model_name", values_to = "model") %>% 
  mutate(summary = map(model, summary),
         rsq = map_dbl(summary, "r.squared")) %>% 
  I()
lm_results
```

## mission hours
```{r}

mission_hours <- astronauts %>% 
  group_by(year_of_mission, mission_title) %>% 
  slice(1) %>% 
  group_by(year_of_mission) %>% 
  summarize(mission_hours = sum(hours_mission, na.rm = TRUE)) %>% 
  rename(year = year_of_mission) %>% 
  left_join(ufos) %>% 
  I()
mission_hours
```

## plot UFOs vs mission hours
```{r}
p2 <- mission_hours %>% 
  ggplot() +
  aes(x = mission_hours, y = sightings) +
  geom_image(aes(image = alien), size=.075)+
  geom_smooth(method = "lm", col = "olivedrab1") +
  labs(x = "Number of astronaut mission hours",
       y = "Number of UFO sightings") +
  truth_theme +
  theme(plot.subtitle = element_text(hjust = -0.5),
             plot.margin = margin(.5, 0.15, .15, 0.15, "cm")) +
  NULL
```

##put plots together & add patchwork annotation
```{r}
p3 <- p1 + p2 +
  plot_annotation(
    title = "Maybe there are Astronauts? Maybe there are Aliens?",
   subtitle = "Chance of there being an Extra-Vehicular Activity on any given hour, and more UFO sightings in years\nwith more astronaut mission hours",
    caption = "\n@gavin_fay\nData: Mariya Stavnichuk and Tatsuya Corlett, NUFORC\nAstronaut & Alien icons by Icons8") &
  truth_theme &
  theme(
    plot.background = element_rect(fill = "black"),
   text = element_text('mono', color = "white"),
   plot.caption = element_text(size = 8),
   plot.title = element_text(size = 18, face = "bold"),
   plot.subtitle = element_text(size = 10)
  )
#p3
ggsave(filename = "astronauts.png", p3, height = 4.5, width = 9)
```
